import Head from "next/head";
import Card from "../components/Card";
import CardProfile from "../components/CardProfile";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>time tracking dashboard_.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={`${styles.cardProfile} ${styles.profile}`}>
            <CardProfile selectDaily={false} selectWeekly={false} selectMonthly={false} />
          </div>

          <div className={`${styles.card} ${styles.work}`}>
            <Card
              icon={undefined}
              title={"Work"}
              current={0}
              previous={0}
              dataReference={"data Reference "}
            />
          </div>
          <div className={`${styles.card} ${styles.play}`}>
            <Card
              icon={undefined}
              title={"Play"}
              current={0}
              previous={0}
              dataReference={"data Reference "}
            />
          </div>
          <div className={`${styles.card} ${styles.study}`}>
            <Card
              icon={undefined}
              title={"Study"}
              current={0}
              previous={0}
              dataReference={"data Reference "}
            />
          </div>
        </div>

        <div className={styles.secondGrid}>
          <div className={`${styles.card} ${styles.exercise}`}>
            <Card
              icon={undefined}
              title={"Exercise"}
              current={0}
              previous={0}
              dataReference={"data Reference "}
            />
          </div>
          <div className={`${styles.card} ${styles.social}`}>
            <Card
              icon={undefined}
              title={"Social"}
              current={0}
              previous={0}
              dataReference={"data Reference "}
            />
          </div>
          <div className={`${styles.card} ${styles.selfCare}`}>
            <Card
              icon={undefined}
              title={"Self Care"}
              current={0}
              previous={0}
              dataReference={"data Reference "}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
